### ISSUE TITLE
Glob with conditional file names

### ISSUE THREAD

**Issue by roykolak** [mtsmfm/split-test#5]
I'm trying to grab all spec files that end in "test.ts" and spec.ts". 

The glob, `/**/*.{test,spec}.ts` isn't doing the trick and it's failing with "Error: Test file is not found". 

Is it possible to pass a glob w/ a conditional match like this?

**Comment by mtsmfm** [comment]
This CLI uses glob crate and it seems it doesn't support curly braces pattern.

https://github.com/rust-lang/glob/issues/2

**Comment by mtsmfm** [comment]
BTW this CLI accepts multiple --tests-glob arg.

`split-test ... --tests-glob '/**/*.test.ts' --tests-glob '/**/*.spec.ts'`

I've added a test for this just in case.

https://github.com/mtsmfm/split-test/commit/45ee4d430ebd16bc0fce7581b38f38d1bb23fbbb

**Comment by roykolak** [comment]
forgot to follow up here, but thanks for the note! Very helpful 👍
